build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,62 +27,62 @@ on:
   
 jobs:
   build-kernel-oneplus-kernelsu-susfs:
-    runs-on: [self-hosted, ubuntu-24.04]
-    env:
-      ACTIONS_RUNNER_DEBUG: true
-      ACTIONS_STEP_DEBUG: true
-      
+    runs-on: ubuntu-latest
+
     steps:
       - name: Setup System
         run: |
-          set -x
           export DEBIAN_FRONTEND=noninteractive
           echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
-          echo "Work directory: $(pwd)"
-          sudo rm -rf * || true
-          sudo rm -rf .[^.]* || true
           
-      - name: Install Python3
-        run: |
-          set -x
-          if ! command -v python3 &> /dev/null; then
-            echo "🔹Python3 not found, updating apt and installing..."
-            sudo apt update
-            sudo apt install -y python3 python-is-python3
-          else
-            echo "🔹Python3 is already installed at $(which python3)"
-          fi
+          df -h
+          
+          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
+          sudo docker image prune --all --force
+          echo "some directories deleted"
+          
+          # Remove large unwanted packages
+          sudo apt-get purge -y \
+            aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+            google-cloud-sdk imagemagick \
+            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+            mercurial apt-transport-https mono-complete libmysqlclient \
+            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+            sphinxsearch subversion mongodb-org microsoft-edge-stable || true
+          
+          # Regex-based purges (for bulk families like mysql, php, dotnet)
+          sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
+          
+          # Clean up
+          sudo apt-get autoremove -y
+          sudo apt-get autoclean -y
+          echo "some packages purged"
+          
+          df -h
 
-      - name: Install Repo
+      - name: Install Repo and Python
         run: |
-          set -x
-          if ! command -v repo &> /dev/null; then
-            echo "🔹Repo not found, installing..."
-            mkdir -p ./git-repo
-            curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
-            chmod a+rx ./git-repo/repo
-            echo "REPO=$GITHUB_WORKSPACE/./git-repo/repo" >> $GITHUB_ENV
-          else
-            echo "🔹Repo is already installed at $(which repo)"
-            echo "REPO=$(which repo)" >> $GITHUB_ENV
-          fi
+          # Install dependencies
+          sudo apt update
+          sudo apt install -y python3 python-is-python3
+          
+          mkdir -p ./git-repo
+          curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
+          chmod a+rx ./git-repo/repo
+          echo "REPO=$GITHUB_WORKSPACE/./git-repo/repo" >> $GITHUB_ENV
 
       - name: Set CONFIG Environment Variable
         run: |
-          set -x
           CONFIG="${{ inputs.model }}"
           
           # Set CONFIG as an environment variable for future steps
           echo "CONFIG=$CONFIG" >> $GITHUB_ENV
           
           echo "CONFIG set to: $CONFIG"
-          
-      - name: Set CONFIG Environment Variable
-        run: |
-          set -x
-          CONFIG="${{ inputs.model }}"
-          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
-          echo "CONFIG set to: $CONFIG"
+
           
       - name: Clone AnyKernel3 and Other Dependencies
         run: |
